package:
  name: "exceptnotifier"
  version: "0.1.7"

source:
  git_rev: v0.1.7
  git_url: https://github.com/dsdanielpark/ExceptNotifier

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - jupyter
    - ipykernel
    - requests



about:
  home: https://github.com/dsdanielpark/ExceptNotifier
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: Integrates AI-assisted debugging notifications into Python try-except statements for various messaging applications."

extra:
  recipe-maintainers:
    - dsdanielpark